package com.researchintelligence.platform.dataquality.domain;

public enum DataQualityIssueType {
    PUBLICATIONS_WITHOUT_DOI,
    PUBLICATIONS_WITHOUT_ABSTRACT,
    PUBLICATIONS_WITHOUT_PUBLIC_SUMMARY,
    PUBLICATIONS_WITHOUT_TOPICS,
    PUBLICATION_TITLE_CASING_ISSUES,
    RESEARCHERS_WITHOUT_ORCID,
    PUBLICATIONS_WITH_EXTERNAL_AUTHORS,
    UNRESOLVED_EXTERNAL_AUTHORS,
    ACTIVITIES_PENDING_VALIDATION,
    VENUES_WITHOUT_IDENTIFIER,
    EVENTS_WITHOUT_DATES,
    EXTERNAL_ORGANIZATION_DUPLICATE_CANDIDATES,
    DUPLICATE_TOPIC_CANDIDATES,
    DUPLICATE_PUBLICATION_CANDIDATES
}
